package com.moshitech.workmate.feature.deviceinfo.utils

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.moshitech.workmate.feature.deviceinfo.viewmodel.PermissionGroup
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

object PermissionReportGenerator {

    fun generateCSV(context: Context, groups: List<PermissionGroup>): File {
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val fileName = "permissions_report_$timestamp.csv"
        val file = File(context.cacheDir, fileName)
        
        file.bufferedWriter().use { writer ->
            // CSV Header
            writer.write("Permission Group,App Name,Package Name,Status\n")
            
            // Data rows
            groups.forEach { group ->
                group.apps.forEach { app ->
                    val status = if (app.isGranted) "Allowed" else "Denied"
                    writer.write("\"${group.name}\",\"${app.appName}\",\"${app.packageName}\",\"$status\"\n")
                }
            }
        }
        
        return file
    }
    
    fun generateTextReport(context: Context, groups: List<PermissionGroup>): File {
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val fileName = "permissions_report_$timestamp.txt"
        val file = File(context.cacheDir, fileName)
        
        file.bufferedWriter().use { writer ->
            writer.write("PERMISSIONS REPORT\n")
            writer.write("Generated: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}\n")
            writer.write("=" * 60 + "\n\n")
            
            groups.forEach { group ->
                writer.write("${group.name.uppercase()}\n")
                writer.write("-" * 60 + "\n")
                
                val allowed = group.apps.filter { it.isGranted }
                val denied = group.apps.filter { !it.isGranted }
                
                if (allowed.isNotEmpty()) {
                    writer.write("\nAllowed (${allowed.size}):\n")
                    allowed.forEach { app ->
                        writer.write("  ✓ ${app.appName}\n")
                        writer.write("    ${app.packageName}\n")
                    }
                }
                
                if (denied.isNotEmpty()) {
                    writer.write("\nDenied (${denied.size}):\n")
                    denied.forEach { app ->
                        writer.write("  ✗ ${app.appName}\n")
                        writer.write("    ${app.packageName}\n")
                    }
                }
                
                writer.write("\n" + "=" * 60 + "\n\n")
            }
            
            // Summary
            val totalApps = groups.flatMap { it.apps }.distinctBy { it.packageName }.size
            val totalPermissions = groups.size
            val totalAllowed = groups.flatMap { it.apps }.count { it.isGranted }
            val totalDenied = groups.flatMap { it.apps }.count { !it.isGranted }
            
            writer.write("SUMMARY\n")
            writer.write("-" * 60 + "\n")
            writer.write("Total Apps: $totalApps\n")
            writer.write("Total Permission Groups: $totalPermissions\n")
            writer.write("Total Allowed: $totalAllowed\n")
            writer.write("Total Denied: $totalDenied\n")
        }
        
        return file
    }
    
    fun shareReport(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
        
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = if (file.extension == "csv") "text/csv" else "text/plain"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "Permissions Report")
            putExtra(Intent.EXTRA_TEXT, "Permissions report generated by Workmate")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        
        context.startActivity(Intent.createChooser(shareIntent, "Share Report"))
    }
}

private operator fun String.times(count: Int): String = this.repeat(count)
